name = "api-fetch-worker"
compatibility_date = "2025-09-27"

[triggers]
crons = ["0 * * * *"]  # Run at the top of every hour

[[kv_namespaces]]
binding = "DATA"
id = "<YOUR_PRODUCTION_NAMESPACE_ID>"
preview_id = "<YOUR_PREVIEW_NAMESPACE_ID>"

[vars]
REPO_OWNER = "Truyem"
REPO_NAME  = "api"
REPO_BRANCH = "main"
